// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-rNEd30aLiy5i6Q4QsjV8ACmrniVPsAg',
    appId: '1:706966856959:android:9f1ba690945c06cda398ca',
    messagingSenderId: '706966856959',
    projectId: 'food-payed',
    storageBucket: 'food-payed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVBgy02tQF3N2aXKtPzKBLpDWvnM3BmT4',
    appId: '1:706966856959:ios:09388a90338fadbfa398ca',
    messagingSenderId: '706966856959',
    projectId: 'food-payed',
    storageBucket: 'food-payed.firebasestorage.app',
    iosBundleId: 'at.glocknerstudios.foodPayed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVBgy02tQF3N2aXKtPzKBLpDWvnM3BmT4',
    appId: '1:706966856959:ios:09388a90338fadbfa398ca',
    messagingSenderId: '706966856959',
    projectId: 'food-payed',
    storageBucket: 'food-payed.firebasestorage.app',
    iosBundleId: 'at.glocknerstudios.foodPayed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXev_5zLkVTfAH8a_F2U-RMjrN4VqYHpI',
    appId: '1:706966856959:web:29535a27da022b73a398ca',
    messagingSenderId: '706966856959',
    projectId: 'food-payed',
    authDomain: 'food-payed.firebaseapp.com',
    storageBucket: 'food-payed.firebasestorage.app',
  );
}
